/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    chapters: Chapter;
    pages: Page;
    committees: Committee;
    forms: Form;
    'form-submissions': FormSubmission;
    posts: Post;
    events: Event;
    albums: Album;
    media: Media;
    documents: Document;
    programs: Program;
    people: Person;
    users: User;
    'page-views': PageView;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    chapters: ChaptersSelect<false> | ChaptersSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    committees: CommitteesSelect<false> | CommitteesSelect<true>;
    forms: FormsSelect<false> | FormsSelect<true>;
    'form-submissions': FormSubmissionsSelect<false> | FormSubmissionsSelect<true>;
    posts: PostsSelect<false> | PostsSelect<true>;
    events: EventsSelect<false> | EventsSelect<true>;
    albums: AlbumsSelect<false> | AlbumsSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    documents: DocumentsSelect<false> | DocumentsSelect<true>;
    programs: ProgramsSelect<false> | ProgramsSelect<true>;
    people: PeopleSelect<false> | PeopleSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'page-views': PageViewsSelect<false> | PageViewsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'site-settings': SiteSetting;
  };
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * The branch and each society chapter / affinity group. Webmasters edit their own.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "chapters".
 */
export interface Chapter {
  id: number;
  layout?:
    | (
        | ChapterAboutBlock
        | TextBlock
        | MediaTextBlock
        | CardsBlock
        | StatsBlock
        | TimelineBlock
        | GalleryBlock
        | EventsBlock
        | StoriesBlock
        | PeopleBlock
        | FaqBlock
        | FormBlock
        | DownloadsBlock
        | LogosBlock
        | VideoBlock
        | PageLinksBlock
        | ScheduleBlock
        | SpeakersBlock
        | FeesBlock
        | VenueBlock
        | CtaBlock
      )[]
    | null;
  name: string;
  /**
   * e.g. CS, ComSoc, WIE
   */
  shortName: string;
  /**
   * Used in the page URL. Leave blank to generate it from the title.
   */
  slug?: string | null;
  kind: 'branch' | 'chapter' | 'affinity';
  tagline?: string | null;
  /**
   * Two or three short paragraphs.
   */
  about?: string | null;
  mission?: string | null;
  /**
   * Chapter colour (hex)
   */
  accent?: string | null;
  founded?: number | null;
  order?: number | null;
  logo?: (number | null) | Media;
  cover?: (number | null) | Media;
  /**
   * Short facts shown as big numbers, e.g. "1st" / "MTT-S chapter in Sri Lanka".
   */
  highlights?:
    | {
        value: string;
        label: string;
        id?: string | null;
      }[]
    | null;
  vtools?: {
    /**
     * Find it in vTools → Events → your chapter. Events hosted or co-hosted by this unit appear on the site automatically.
     */
    spoid?: string | null;
    /**
     * Fallback when the SPOID is empty: events whose host name contains this text are matched (e.g. "Peradeniya").
     */
    hostNameMatch?: string | null;
  };
  links?: {
    email?: string | null;
    website?: string | null;
    facebook?: string | null;
    instagram?: string | null;
    linkedin?: string | null;
    join?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ChapterAboutBlock".
 */
export interface ChapterAboutBlock {
  /**
   * Takes it off the page but keeps everything here, ready to switch back on. The On/Off switch on the collapsed row does the same.
   */
  hidden?: boolean | null;
  /**
   * Defaults to “What is <chapter>?”. Text comes from the About, Mission, Highlights and Links fields.
   */
  heading?: string | null;
  background?: ('auto' | 'paper' | 'mist' | 'dark' | 'accent') | null;
  spacing?: ('normal' | 'compact') | null;
  /**
   * Optional link name, e.g. “rules” → /page#rules
   */
  anchor?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'chapterAbout';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TextBlock".
 */
export interface TextBlock {
  /**
   * Takes it off the page but keeps everything here, ready to switch back on. The On/Off switch on the collapsed row does the same.
   */
  hidden?: boolean | null;
  /**
   * Small label above the heading (optional)
   */
  eyebrow?: string | null;
  heading?: string | null;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  width?: ('narrow' | 'split') | null;
  background?: ('auto' | 'paper' | 'mist' | 'dark' | 'accent') | null;
  spacing?: ('normal' | 'compact') | null;
  /**
   * Optional link name, e.g. “rules” → /page#rules
   */
  anchor?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'text';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "MediaTextBlock".
 */
export interface MediaTextBlock {
  /**
   * Takes it off the page but keeps everything here, ready to switch back on. The On/Off switch on the collapsed row does the same.
   */
  hidden?: boolean | null;
  /**
   * Small label above the heading (optional)
   */
  eyebrow?: string | null;
  heading?: string | null;
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  image: number | Media;
  imageSide?: ('left' | 'right') | null;
  buttons?:
    | {
        label: string;
        /**
         * https://… or /chapters/…
         */
        url: string;
        variant?: ('primary' | 'secondary') | null;
        id?: string | null;
      }[]
    | null;
  background?: ('auto' | 'paper' | 'mist' | 'dark' | 'accent') | null;
  spacing?: ('normal' | 'compact') | null;
  /**
   * Optional link name, e.g. “rules” → /page#rules
   */
  anchor?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'mediaText';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * What the image shows, for screen readers and search. For a poster, type the text on it (title, date, venue).
   */
  alt: string;
  credit?: string | null;
  chapter?: (number | null) | Chapter;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumb?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    hero?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CardsBlock".
 */
export interface CardsBlock {
  /**
   * Takes it off the page but keeps everything here, ready to switch back on. The On/Off switch on the collapsed row does the same.
   */
  hidden?: boolean | null;
  /**
   * Small label above the heading (optional)
   */
  eyebrow?: string | null;
  heading?: string | null;
  intro?: string | null;
  columns?: ('2' | '3' | '4') | null;
  /**
   * Tracks, prize categories, rounds, projects, benefits…
   */
  items?:
    | {
        title: string;
        /**
         * Small label, e.g. “1st place”, “Round 2”
         */
        tag?: string | null;
        text?: string | null;
        image?: (number | null) | Media;
        /**
         * Optional link
         */
        link?: string | null;
        id?: string | null;
      }[]
    | null;
  background?: ('auto' | 'paper' | 'mist' | 'dark' | 'accent') | null;
  spacing?: ('normal' | 'compact') | null;
  /**
   * Optional link name, e.g. “rules” → /page#rules
   */
  anchor?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'cards';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "StatsBlock".
 */
export interface StatsBlock {
  /**
   * Takes it off the page but keeps everything here, ready to switch back on. The On/Off switch on the collapsed row does the same.
   */
  hidden?: boolean | null;
  /**
   * Small label above the heading (optional)
   */
  eyebrow?: string | null;
  heading?: string | null;
  items?:
    | {
        value: string;
        label: string;
        id?: string | null;
      }[]
    | null;
  background?: ('auto' | 'paper' | 'mist' | 'dark' | 'accent') | null;
  spacing?: ('normal' | 'compact') | null;
  /**
   * Optional link name, e.g. “rules” → /page#rules
   */
  anchor?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'stats';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TimelineBlock".
 */
export interface TimelineBlock {
  /**
   * Takes it off the page but keeps everything here, ready to switch back on. The On/Off switch on the collapsed row does the same.
   */
  hidden?: boolean | null;
  /**
   * Small label above the heading (optional)
   */
  eyebrow?: string | null;
  heading?: string | null;
  items?:
    | {
        when: string;
        title: string;
        text?: string | null;
        id?: string | null;
      }[]
    | null;
  background?: ('auto' | 'paper' | 'mist' | 'dark' | 'accent') | null;
  spacing?: ('normal' | 'compact') | null;
  /**
   * Optional link name, e.g. “rules” → /page#rules
   */
  anchor?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'timeline';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "GalleryBlock".
 */
export interface GalleryBlock {
  /**
   * Takes it off the page but keeps everything here, ready to switch back on. The On/Off switch on the collapsed row does the same.
   */
  hidden?: boolean | null;
  /**
   * Small label above the heading (optional)
   */
  eyebrow?: string | null;
  heading?: string | null;
  /**
   * Pick photos — or leave empty and choose an album below. Both empty: your chapter’s albums.
   */
  photos?: (number | Media)[] | null;
  album?: (number | null) | Album;
  layout?: ('mosaic' | 'rows') | null;
  background?: ('auto' | 'paper' | 'mist' | 'dark' | 'accent') | null;
  spacing?: ('normal' | 'compact') | null;
  /**
   * Optional link name, e.g. “rules” → /page#rules
   */
  anchor?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'gallery';
}
/**
 * Upload event photos here — they appear in the gallery and on your chapter page.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "albums".
 */
export interface Album {
  id: number;
  title: string;
  date?: string | null;
  description?: string | null;
  photos: (number | Media)[];
  /**
   * Used in the page URL. Leave blank to generate it from the title.
   */
  slug?: string | null;
  /**
   * Filled in with your chapter automatically. Only branch webmasters can change it.
   */
  chapter: number | Chapter;
  updatedAt: string;
  createdAt: string;
  deletedAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "EventsBlock".
 */
export interface EventsBlock {
  /**
   * Takes it off the page but keeps everything here, ready to switch back on. The On/Off switch on the collapsed row does the same.
   */
  hidden?: boolean | null;
  /**
   * Small label above the heading (optional)
   */
  eyebrow?: string | null;
  heading?: string | null;
  show?: ('auto' | 'upcoming' | 'past') | null;
  limit?: number | null;
  /**
   * Only events whose title contains this, e.g. “RoboFest”
   */
  titleContains?: string | null;
  background?: ('auto' | 'paper' | 'mist' | 'dark' | 'accent') | null;
  spacing?: ('normal' | 'compact') | null;
  /**
   * Optional link name, e.g. “rules” → /page#rules
   */
  anchor?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'events';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "StoriesBlock".
 */
export interface StoriesBlock {
  /**
   * Takes it off the page but keeps everything here, ready to switch back on. The On/Off switch on the collapsed row does the same.
   */
  hidden?: boolean | null;
  /**
   * Small label above the heading (optional)
   */
  eyebrow?: string | null;
  heading?: string | null;
  limit?: number | null;
  /**
   * Only stories whose title contains this
   */
  titleContains?: string | null;
  background?: ('auto' | 'paper' | 'mist' | 'dark' | 'accent') | null;
  spacing?: ('normal' | 'compact') | null;
  /**
   * Optional link name, e.g. “rules” → /page#rules
   */
  anchor?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'stories';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "PeopleBlock".
 */
export interface PeopleBlock {
  /**
   * Takes it off the page but keeps everything here, ready to switch back on. The On/Off switch on the collapsed row does the same.
   */
  hidden?: boolean | null;
  /**
   * Small label above the heading (optional)
   */
  eyebrow?: string | null;
  heading?: string | null;
  source?: ('committee' | 'custom') | null;
  items?:
    | {
        name: string;
        /**
         * Role, e.g. “Head judge”
         */
        position?: string | null;
        organisation?: string | null;
        linkedin?: string | null;
        photo?: (number | null) | Media;
        id?: string | null;
      }[]
    | null;
  background?: ('auto' | 'paper' | 'mist' | 'dark' | 'accent') | null;
  spacing?: ('normal' | 'compact') | null;
  /**
   * Optional link name, e.g. “rules” → /page#rules
   */
  anchor?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'people';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FaqBlock".
 */
export interface FaqBlock {
  /**
   * Takes it off the page but keeps everything here, ready to switch back on. The On/Off switch on the collapsed row does the same.
   */
  hidden?: boolean | null;
  /**
   * Small label above the heading (optional)
   */
  eyebrow?: string | null;
  heading?: string | null;
  items?:
    | {
        q: string;
        a: string;
        id?: string | null;
      }[]
    | null;
  background?: ('auto' | 'paper' | 'mist' | 'dark' | 'accent') | null;
  spacing?: ('normal' | 'compact') | null;
  /**
   * Optional link name, e.g. “rules” → /page#rules
   */
  anchor?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'faq';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FormBlock".
 */
export interface FormBlock {
  /**
   * Takes it off the page but keeps everything here, ready to switch back on. The On/Off switch on the collapsed row does the same.
   */
  hidden?: boolean | null;
  /**
   * Small label above the heading (optional)
   */
  eyebrow?: string | null;
  heading?: string | null;
  intro?: string | null;
  form: number | Form;
  background?: ('auto' | 'paper' | 'mist' | 'dark' | 'accent') | null;
  spacing?: ('normal' | 'compact') | null;
  /**
   * Optional link name, e.g. “rules” → /page#rules
   */
  anchor?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'form';
}
/**
 * Build a form, then add it to any page with the “Form” section — or share its own link (/forms/<address>).
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "forms".
 */
export interface Form {
  id: number;
  title: string;
  /**
   * Shown above the questions on the form’s own page.
   */
  intro?: string | null;
  fields?:
    | (
        | {
            label: string;
            width?: ('full' | 'half') | null;
            required?: boolean | null;
            /**
             * Shown under the question (optional)
             */
            help?: string | null;
            name?: string | null;
            placeholder?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'shortText';
          }
        | {
            label: string;
            width?: ('full' | 'half') | null;
            required?: boolean | null;
            /**
             * Shown under the question (optional)
             */
            help?: string | null;
            name?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'email';
          }
        | {
            label: string;
            width?: ('full' | 'half') | null;
            required?: boolean | null;
            /**
             * Shown under the question (optional)
             */
            help?: string | null;
            name?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'phone';
          }
        | {
            label: string;
            width?: ('full' | 'half') | null;
            required?: boolean | null;
            /**
             * Shown under the question (optional)
             */
            help?: string | null;
            name?: string | null;
            min?: number | null;
            max?: number | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'number';
          }
        | {
            label: string;
            width?: ('full' | 'half') | null;
            required?: boolean | null;
            /**
             * Shown under the question (optional)
             */
            help?: string | null;
            name?: string | null;
            placeholder?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'longText';
          }
        | {
            label: string;
            width?: ('full' | 'half') | null;
            required?: boolean | null;
            /**
             * Shown under the question (optional)
             */
            help?: string | null;
            name?: string | null;
            options?:
              | {
                  label: string;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'select';
          }
        | {
            label: string;
            width?: ('full' | 'half') | null;
            required?: boolean | null;
            /**
             * Shown under the question (optional)
             */
            help?: string | null;
            name?: string | null;
            options?:
              | {
                  label: string;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'radio';
          }
        | {
            label: string;
            width?: ('full' | 'half') | null;
            required?: boolean | null;
            /**
             * Shown under the question (optional)
             */
            help?: string | null;
            name?: string | null;
            options?:
              | {
                  label: string;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'checkboxes';
          }
        | {
            label: string;
            width?: ('full' | 'half') | null;
            required?: boolean | null;
            /**
             * Shown under the question (optional)
             */
            help?: string | null;
            name?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'date';
          }
        | {
            label: string;
            width?: ('full' | 'half') | null;
            required?: boolean | null;
            /**
             * Shown under the question (optional)
             */
            help?: string | null;
            name?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'url';
          }
        | {
            label: string;
            width?: ('full' | 'half') | null;
            required?: boolean | null;
            /**
             * Shown under the question (optional)
             */
            help?: string | null;
            name?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'consent';
          }
        | {
            label: string;
            help?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'section';
          }
      )[]
    | null;
  submitLabel?: string | null;
  confirmationTitle?: string | null;
  confirmationMessage?: string | null;
  /**
   * Optional
   */
  opensAt?: string | null;
  /**
   * Optional — the form closes itself
   */
  closesAt?: string | null;
  /**
   * Optional cap, e.g. 60 seats
   */
  maxResponses?: number | null;
  /**
   * Needs an Email question
   */
  onePerEmail?: boolean | null;
  status?: ('open' | 'closed') | null;
  /**
   * Used in the page URL. Leave blank to generate it from the title.
   */
  slug?: string | null;
  /**
   * Filled in with your chapter automatically. Only branch webmasters can change it.
   */
  chapter: number | Chapter;
  updatedAt: string;
  createdAt: string;
  deletedAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "DownloadsBlock".
 */
export interface DownloadsBlock {
  /**
   * Takes it off the page but keeps everything here, ready to switch back on. The On/Off switch on the collapsed row does the same.
   */
  hidden?: boolean | null;
  /**
   * Small label above the heading (optional)
   */
  eyebrow?: string | null;
  heading?: string | null;
  items?:
    | {
        label: string;
        note?: string | null;
        file: number | Document;
        id?: string | null;
      }[]
    | null;
  background?: ('auto' | 'paper' | 'mist' | 'dark' | 'accent') | null;
  spacing?: ('normal' | 'compact') | null;
  /**
   * Optional link name, e.g. “rules” → /page#rules
   */
  anchor?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'downloads';
}
/**
 * PDFs and other files for the Downloads section (max 20 MB each).
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "documents".
 */
export interface Document {
  id: number;
  title: string;
  chapter?: (number | null) | Chapter;
  updatedAt: string;
  createdAt: string;
  deletedAt?: string | null;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "LogosBlock".
 */
export interface LogosBlock {
  /**
   * Takes it off the page but keeps everything here, ready to switch back on. The On/Off switch on the collapsed row does the same.
   */
  hidden?: boolean | null;
  /**
   * Small label above the heading (optional)
   */
  eyebrow?: string | null;
  heading?: string | null;
  items?:
    | {
        name: string;
        /**
         * Groups logos, e.g. “Title sponsor”
         */
        tier?: string | null;
        url?: string | null;
        logo: number | Media;
        id?: string | null;
      }[]
    | null;
  background?: ('auto' | 'paper' | 'mist' | 'dark' | 'accent') | null;
  spacing?: ('normal' | 'compact') | null;
  /**
   * Optional link name, e.g. “rules” → /page#rules
   */
  anchor?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'logos';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "VideoBlock".
 */
export interface VideoBlock {
  /**
   * Takes it off the page but keeps everything here, ready to switch back on. The On/Off switch on the collapsed row does the same.
   */
  hidden?: boolean | null;
  /**
   * Small label above the heading (optional)
   */
  eyebrow?: string | null;
  heading?: string | null;
  /**
   * The video link or its ID
   */
  youtube: string;
  caption?: string | null;
  background?: ('auto' | 'paper' | 'mist' | 'dark' | 'accent') | null;
  spacing?: ('normal' | 'compact') | null;
  /**
   * Optional link name, e.g. “rules” → /page#rules
   */
  anchor?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'video';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "PageLinksBlock".
 */
export interface PageLinksBlock {
  /**
   * Takes it off the page but keeps everything here, ready to switch back on. The On/Off switch on the collapsed row does the same.
   */
  hidden?: boolean | null;
  /**
   * Small label above the heading (optional)
   */
  eyebrow?: string | null;
  heading?: string | null;
  /**
   * Leave empty to show every published sub-page of this chapter (or of this page).
   */
  pages?: (number | Page)[] | null;
  background?: ('auto' | 'paper' | 'mist' | 'dark' | 'accent') | null;
  spacing?: ('normal' | 'compact') | null;
  /**
   * Optional link name, e.g. “rules” → /page#rules
   */
  anchor?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'pageLinks';
}
/**
 * Sub-pages under your chapter: a flagship competition, a project, an info page. Start from a template, then add, remove and drag sections.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  /**
   * Fills the page with starter sections. Replace the [bracketed] text, delete what you don’t need.
   */
  template?: ('competition' | 'conference' | 'project' | 'info' | 'blank') | null;
  layout?:
    | (
        | HeroBlock
        | TextBlock
        | MediaTextBlock
        | CardsBlock
        | StatsBlock
        | TimelineBlock
        | GalleryBlock
        | EventsBlock
        | StoriesBlock
        | PeopleBlock
        | FaqBlock
        | FormBlock
        | DownloadsBlock
        | LogosBlock
        | VideoBlock
        | PageLinksBlock
        | ScheduleBlock
        | SpeakersBlock
        | FeesBlock
        | VenueBlock
        | CtaBlock
      )[]
    | null;
  /**
   * One or two sentences for the card.
   */
  summary?: string | null;
  /**
   * Card image. Falls back to the header photo.
   */
  cover?: (number | null) | Media;
  /**
   * A conference or flagship brand colour. Leave empty to use the chapter colour.
   */
  accent?: string | null;
  showInNav?: boolean | null;
  /**
   * Lower comes first
   */
  order?: number | null;
  /**
   * Optional: put this page under another page, e.g. “Rules” under “RoboFest”.
   */
  parent?: (number | null) | Page;
  /**
   * Defaults to the page title
   */
  metaTitle?: string | null;
  /**
   * Shown in Google and link previews. Defaults to the card text.
   */
  metaDescription?: string | null;
  /**
   * Page address. Leave blank to use the title.
   */
  slug?: string | null;
  /**
   * Full address on the site
   */
  path?: string | null;
  /**
   * Branch webmaster only. Makes the page open at ieee.soc.pdn.ac.lk/<short address> — for conferences and flagships printed on posters. Its sub-pages follow (/conf2026/registration).
   */
  shortPath?: string | null;
  /**
   * The address visitors see
   */
  url?: string | null;
  /**
   * Filled in with your chapter automatically. Only branch webmasters can change it.
   */
  chapter: number | Chapter;
  updatedAt: string;
  createdAt: string;
  deletedAt?: string | null;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HeroBlock".
 */
export interface HeroBlock {
  /**
   * Takes it off the page but keeps everything here, ready to switch back on. The On/Off switch on the collapsed row does the same.
   */
  hidden?: boolean | null;
  /**
   * Small label above the heading (optional)
   */
  eyebrow?: string | null;
  heading: string;
  text?: string | null;
  /**
   * Wide background photo (≥ 1920 px)
   */
  image?: (number | null) | Media;
  /**
   * e.g. “12–13 Dec 2026 · E-Faculty”
   */
  dateLabel?: string | null;
  /**
   * Shows a live countdown until this moment
   */
  countdownTo?: string | null;
  buttons?:
    | {
        label: string;
        /**
         * https://… or /chapters/…
         */
        url: string;
        variant?: ('primary' | 'secondary') | null;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'hero';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ScheduleBlock".
 */
export interface ScheduleBlock {
  /**
   * Takes it off the page but keeps everything here, ready to switch back on. The On/Off switch on the collapsed row does the same.
   */
  hidden?: boolean | null;
  /**
   * Small label above the heading (optional)
   */
  eyebrow?: string | null;
  heading?: string | null;
  intro?: string | null;
  days?:
    | {
        label: string;
        date?: string | null;
        /**
         * In time order. Slots with the same start time are shown side by side as parallel sessions.
         */
        slots?:
          | {
              time: string;
              end?: string | null;
              kind?: ('session' | 'keynote' | 'workshop' | 'break' | 'ceremony') | null;
              title: string;
              /**
               * Speaker, chair or presenters
               */
              speaker?: string | null;
              /**
               * Room or track, e.g. “Hall A · Track 1”
               */
              room?: string | null;
              description?: string | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  background?: ('auto' | 'paper' | 'mist' | 'dark' | 'accent') | null;
  spacing?: ('normal' | 'compact') | null;
  /**
   * Optional link name, e.g. “rules” → /page#rules
   */
  anchor?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'schedule';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "SpeakersBlock".
 */
export interface SpeakersBlock {
  /**
   * Takes it off the page but keeps everything here, ready to switch back on. The On/Off switch on the collapsed row does the same.
   */
  hidden?: boolean | null;
  /**
   * Small label above the heading (optional)
   */
  eyebrow?: string | null;
  heading?: string | null;
  columns?: ('2' | '3' | '4') | null;
  items?:
    | {
        name: string;
        position?: string | null;
        affiliation?: string | null;
        talk?: string | null;
        photo?: (number | null) | Media;
        /**
         * Shown when a visitor opens the speaker. A blank line starts a new paragraph.
         */
        bio?: string | null;
        /**
         * Profile page, Google Scholar or LinkedIn (optional)
         */
        link?: string | null;
        id?: string | null;
      }[]
    | null;
  background?: ('auto' | 'paper' | 'mist' | 'dark' | 'accent') | null;
  spacing?: ('normal' | 'compact') | null;
  /**
   * Optional link name, e.g. “rules” → /page#rules
   */
  anchor?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'speakers';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FeesBlock".
 */
export interface FeesBlock {
  /**
   * Takes it off the page but keeps everything here, ready to switch back on. The On/Off switch on the collapsed row does the same.
   */
  hidden?: boolean | null;
  /**
   * Small label above the heading (optional)
   */
  eyebrow?: string | null;
  heading?: string | null;
  intro?: string | null;
  /**
   * e.g. “Early bird · until 1 Nov”
   */
  column1: string;
  column2?: string | null;
  /**
   * Optional, e.g. “On the day”
   */
  column3?: string | null;
  rows?:
    | {
        category: string;
        highlight?: boolean | null;
        note?: string | null;
        price1: string;
        price2?: string | null;
        price3?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * What the fee includes, payment method, refund policy…
   */
  footnote?: string | null;
  buttons?:
    | {
        label: string;
        /**
         * https://… or /chapters/…
         */
        url: string;
        variant?: ('primary' | 'secondary') | null;
        id?: string | null;
      }[]
    | null;
  background?: ('auto' | 'paper' | 'mist' | 'dark' | 'accent') | null;
  spacing?: ('normal' | 'compact') | null;
  /**
   * Optional link name, e.g. “rules” → /page#rules
   */
  anchor?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'fees';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "VenueBlock".
 */
export interface VenueBlock {
  /**
   * Takes it off the page but keeps everything here, ready to switch back on. The On/Off switch on the collapsed row does the same.
   */
  hidden?: boolean | null;
  /**
   * Small label above the heading (optional)
   */
  eyebrow?: string | null;
  heading?: string | null;
  venueName: string;
  /**
   * What to search on the map. Defaults to the name and address.
   */
  mapQuery?: string | null;
  address?: string | null;
  /**
   * A photo of the venue. Without one, the map is shown in its place.
   */
  image?: (number | null) | Media;
  showMap?: boolean | null;
  /**
   * Getting here, accommodation, visas, parking…
   */
  notes?:
    | {
        title: string;
        text: string;
        id?: string | null;
      }[]
    | null;
  background?: ('auto' | 'paper' | 'mist' | 'dark' | 'accent') | null;
  spacing?: ('normal' | 'compact') | null;
  /**
   * Optional link name, e.g. “rules” → /page#rules
   */
  anchor?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'venue';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CtaBlock".
 */
export interface CtaBlock {
  /**
   * Takes it off the page but keeps everything here, ready to switch back on. The On/Off switch on the collapsed row does the same.
   */
  hidden?: boolean | null;
  heading: string;
  text?: string | null;
  buttons?:
    | {
        label: string;
        /**
         * https://… or /chapters/…
         */
        url: string;
        variant?: ('primary' | 'secondary') | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Optional link name, e.g. “register” → /page#register
   */
  anchor?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'cta';
}
/**
 * One committee per year. Drag rows to reorder. At handover use ⋯ → Duplicate, change the term, tick “On the website” on the new one — last year’s stays as history.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "committees".
 */
export interface Committee {
  id: number;
  title?: string | null;
  /**
   * e.g. 2025/26
   */
  term: string;
  /**
   * The committee shown on your chapter page. Ticking it here unticks the others.
   */
  current?: boolean | null;
  advisors?:
    | {
        name: string;
        position?: string | null;
        /**
         * Head-and-shoulders portrait. Shown 4:5 with the face in the top third.
         */
        photo?: (number | null) | Media;
        linkedin?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Order = order on the page. The row whose position is exactly “Chair” (or Chairman / Chairperson / President) gets the spotlight card.
   */
  executive?:
    | {
        position: string;
        name: string;
        /**
         * Head-and-shoulders portrait. Shown 4:5 with the face in the top third.
         */
        photo?: (number | null) | Media;
        linkedin?: string | null;
        /**
         * Not shown publicly.
         */
        email?: string | null;
        id?: string | null;
      }[]
    | null;
  teams?:
    | {
        name: string;
        members?:
          | {
              name: string;
              role?: ('lead' | 'member') | null;
              position?: string | null;
              /**
               * Head-and-shoulders portrait. Shown 4:5 with the face in the top third.
               */
              photo?: (number | null) | Media;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Filled in with your chapter automatically. Only branch webmasters can change it.
   */
  chapter: number | Chapter;
  updatedAt: string;
  createdAt: string;
  deletedAt?: string | null;
}
/**
 * Every response to your forms. Download them as CSV from the form’s Responses tab.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-submissions".
 */
export interface FormSubmission {
  id: number;
  summary?: string | null;
  form: number | Form;
  email?: string | null;
  data?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  chapter?: (number | null) | Chapter;
  updatedAt: string;
  createdAt: string;
}
/**
 * Editors write drafts; chapter webmasters publish. Published posts go live instantly.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: number;
  title: string;
  kind?: ('recap' | 'announcement' | 'story' | 'achievement') | null;
  date: string;
  /**
   * Shown on cards. ≤ 320 characters.
   */
  excerpt?: string | null;
  cover?: (number | null) | Media;
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Extra photos shown under the article.
   */
  gallery?: (number | Media)[] | null;
  cta?: {
    label?: string | null;
    url?: string | null;
  };
  /**
   * Used in the page URL. Leave blank to generate it from the title.
   */
  slug?: string | null;
  /**
   * Filled in with your chapter automatically. Only branch webmasters can change it.
   */
  chapter: number | Chapter;
  /**
   * The branch webmaster reviews requests and features the best ones.
   */
  featureRequest?: boolean | null;
  /**
   * Branch webmasters only.
   */
  featured?: boolean | null;
  updatedAt: string;
  createdAt: string;
  deletedAt?: string | null;
  _status?: ('draft' | 'published') | null;
}
/**
 * Events sync automatically from IEEE vTools every 30 minutes. Edit title/date/venue in vTools; here you can add a cover photo, hide an event or request it on the home page.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events".
 */
export interface Event {
  id: number;
  title: string;
  start: string;
  end?: string | null;
  category?: ('talk' | 'workshop' | 'competition' | 'visit' | 'social' | 'meeting') | null;
  summary?: string | null;
  descriptionHtml?: string | null;
  venue?: string | null;
  city?: string | null;
  virtual?: boolean | null;
  registrationUrl?: string | null;
  vtoolsUrl?: string | null;
  /**
   * The poster or best photo. Filled in from vTools automatically when the event has images there.
   */
  cover?: (number | null) | Media;
  /**
   * Photos shown on the event page. vTools photos are copied here on the first sync.
   */
  gallery?: (number | Media)[] | null;
  vtoolsMediaDone?: boolean | null;
  /**
   * Hide this event from the website.
   */
  hidden?: boolean | null;
  source?: ('vtools' | 'manual') | null;
  vtoolsId?: string | null;
  hostName?: string | null;
  syncedAt?: string | null;
  /**
   * Used in the page URL. Leave blank to generate it from the title.
   */
  slug?: string | null;
  /**
   * Filled in with your chapter automatically. Only branch webmasters can change it.
   */
  chapter: number | Chapter;
  /**
   * The branch webmaster reviews requests and features the best ones.
   */
  featureRequest?: boolean | null;
  /**
   * Branch webmasters only.
   */
  featured?: boolean | null;
  updatedAt: string;
  createdAt: string;
  deletedAt?: string | null;
}
/**
 * Branch-wide flagship programmes (Pera Xtreme, Predicta, MentorSpark…).
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "programs".
 */
export interface Program {
  id: number;
  name: string;
  /**
   * e.g. “Predicta 1.0”, “Pera.Xtreme-24”
   */
  edition?: string | null;
  /**
   * Used in the page URL. Leave blank to generate it from the title.
   */
  slug?: string | null;
  tagline: string;
  summary: string;
  accent?: string | null;
  order?: number | null;
  cover?: (number | null) | Media;
  logo?: (number | null) | Media;
  stats?:
    | {
        value: string;
        label: string;
        id?: string | null;
      }[]
    | null;
  sections?:
    | {
        heading: string;
        body: string;
        points?:
          | {
              text: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  links?:
    | {
        label: string;
        url: string;
        primary?: boolean | null;
        id?: string | null;
      }[]
    | null;
  contacts?:
    | {
        name: string;
        role?: string | null;
        email?: string | null;
        id?: string | null;
      }[]
    | null;
  gallery?: (number | Media)[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Legacy list — committees are now edited under Your chapter → Committees.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "people".
 */
export interface Person {
  id: number;
  name: string;
  position: string;
  group: 'advisor' | 'executive' | 'lead' | 'member';
  /**
   * e.g. Design, Editorial, Programming
   */
  team?: string | null;
  order?: number | null;
  photo?: (number | null) | Media;
  term?: string | null;
  linkedin?: string | null;
  email?: string | null;
  /**
   * Hide from the current team (kept for history).
   */
  archived?: boolean | null;
  /**
   * Filled in with your chapter automatically. Only branch webmasters can change it.
   */
  chapter: number | Chapter;
  updatedAt: string;
  createdAt: string;
}
/**
 * Branch webmasters invite chapter webmasters and editors here. Each account is locked to one chapter.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name: string;
  role: 'admin' | 'webmaster' | 'editor';
  /**
   * Required for chapter webmasters and editors.
   */
  chapter?: (number | null) | Chapter;
  /**
   * The dashboard reminds this person to hand over to the next committee before this date.
   */
  termEnds?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  resetPasswordRequestedAt?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "page-views".
 */
export interface PageView {
  id: number;
  day: string;
  path: string;
  chapter?: (number | null) | Chapter;
  source?: string | null;
  device?: ('mobile' | 'tablet' | 'desktop') | null;
  visitor?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'chapters';
        value: number | Chapter;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'committees';
        value: number | Committee;
      } | null)
    | ({
        relationTo: 'forms';
        value: number | Form;
      } | null)
    | ({
        relationTo: 'form-submissions';
        value: number | FormSubmission;
      } | null)
    | ({
        relationTo: 'posts';
        value: number | Post;
      } | null)
    | ({
        relationTo: 'events';
        value: number | Event;
      } | null)
    | ({
        relationTo: 'albums';
        value: number | Album;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'documents';
        value: number | Document;
      } | null)
    | ({
        relationTo: 'programs';
        value: number | Program;
      } | null)
    | ({
        relationTo: 'people';
        value: number | Person;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'page-views';
        value: number | PageView;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "chapters_select".
 */
export interface ChaptersSelect<T extends boolean = true> {
  layout?:
    | T
    | {
        chapterAbout?: T | ChapterAboutBlockSelect<T>;
        text?: T | TextBlockSelect<T>;
        mediaText?: T | MediaTextBlockSelect<T>;
        cards?: T | CardsBlockSelect<T>;
        stats?: T | StatsBlockSelect<T>;
        timeline?: T | TimelineBlockSelect<T>;
        gallery?: T | GalleryBlockSelect<T>;
        events?: T | EventsBlockSelect<T>;
        stories?: T | StoriesBlockSelect<T>;
        people?: T | PeopleBlockSelect<T>;
        faq?: T | FaqBlockSelect<T>;
        form?: T | FormBlockSelect<T>;
        downloads?: T | DownloadsBlockSelect<T>;
        logos?: T | LogosBlockSelect<T>;
        video?: T | VideoBlockSelect<T>;
        pageLinks?: T | PageLinksBlockSelect<T>;
        schedule?: T | ScheduleBlockSelect<T>;
        speakers?: T | SpeakersBlockSelect<T>;
        fees?: T | FeesBlockSelect<T>;
        venue?: T | VenueBlockSelect<T>;
        cta?: T | CtaBlockSelect<T>;
      };
  name?: T;
  shortName?: T;
  slug?: T;
  kind?: T;
  tagline?: T;
  about?: T;
  mission?: T;
  accent?: T;
  founded?: T;
  order?: T;
  logo?: T;
  cover?: T;
  highlights?:
    | T
    | {
        value?: T;
        label?: T;
        id?: T;
      };
  vtools?:
    | T
    | {
        spoid?: T;
        hostNameMatch?: T;
      };
  links?:
    | T
    | {
        email?: T;
        website?: T;
        facebook?: T;
        instagram?: T;
        linkedin?: T;
        join?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ChapterAboutBlock_select".
 */
export interface ChapterAboutBlockSelect<T extends boolean = true> {
  hidden?: T;
  heading?: T;
  background?: T;
  spacing?: T;
  anchor?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TextBlock_select".
 */
export interface TextBlockSelect<T extends boolean = true> {
  hidden?: T;
  eyebrow?: T;
  heading?: T;
  content?: T;
  width?: T;
  background?: T;
  spacing?: T;
  anchor?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "MediaTextBlock_select".
 */
export interface MediaTextBlockSelect<T extends boolean = true> {
  hidden?: T;
  eyebrow?: T;
  heading?: T;
  content?: T;
  image?: T;
  imageSide?: T;
  buttons?:
    | T
    | {
        label?: T;
        url?: T;
        variant?: T;
        id?: T;
      };
  background?: T;
  spacing?: T;
  anchor?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CardsBlock_select".
 */
export interface CardsBlockSelect<T extends boolean = true> {
  hidden?: T;
  eyebrow?: T;
  heading?: T;
  intro?: T;
  columns?: T;
  items?:
    | T
    | {
        title?: T;
        tag?: T;
        text?: T;
        image?: T;
        link?: T;
        id?: T;
      };
  background?: T;
  spacing?: T;
  anchor?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "StatsBlock_select".
 */
export interface StatsBlockSelect<T extends boolean = true> {
  hidden?: T;
  eyebrow?: T;
  heading?: T;
  items?:
    | T
    | {
        value?: T;
        label?: T;
        id?: T;
      };
  background?: T;
  spacing?: T;
  anchor?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TimelineBlock_select".
 */
export interface TimelineBlockSelect<T extends boolean = true> {
  hidden?: T;
  eyebrow?: T;
  heading?: T;
  items?:
    | T
    | {
        when?: T;
        title?: T;
        text?: T;
        id?: T;
      };
  background?: T;
  spacing?: T;
  anchor?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "GalleryBlock_select".
 */
export interface GalleryBlockSelect<T extends boolean = true> {
  hidden?: T;
  eyebrow?: T;
  heading?: T;
  photos?: T;
  album?: T;
  layout?: T;
  background?: T;
  spacing?: T;
  anchor?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "EventsBlock_select".
 */
export interface EventsBlockSelect<T extends boolean = true> {
  hidden?: T;
  eyebrow?: T;
  heading?: T;
  show?: T;
  limit?: T;
  titleContains?: T;
  background?: T;
  spacing?: T;
  anchor?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "StoriesBlock_select".
 */
export interface StoriesBlockSelect<T extends boolean = true> {
  hidden?: T;
  eyebrow?: T;
  heading?: T;
  limit?: T;
  titleContains?: T;
  background?: T;
  spacing?: T;
  anchor?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "PeopleBlock_select".
 */
export interface PeopleBlockSelect<T extends boolean = true> {
  hidden?: T;
  eyebrow?: T;
  heading?: T;
  source?: T;
  items?:
    | T
    | {
        name?: T;
        position?: T;
        organisation?: T;
        linkedin?: T;
        photo?: T;
        id?: T;
      };
  background?: T;
  spacing?: T;
  anchor?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FaqBlock_select".
 */
export interface FaqBlockSelect<T extends boolean = true> {
  hidden?: T;
  eyebrow?: T;
  heading?: T;
  items?:
    | T
    | {
        q?: T;
        a?: T;
        id?: T;
      };
  background?: T;
  spacing?: T;
  anchor?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FormBlock_select".
 */
export interface FormBlockSelect<T extends boolean = true> {
  hidden?: T;
  eyebrow?: T;
  heading?: T;
  intro?: T;
  form?: T;
  background?: T;
  spacing?: T;
  anchor?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "DownloadsBlock_select".
 */
export interface DownloadsBlockSelect<T extends boolean = true> {
  hidden?: T;
  eyebrow?: T;
  heading?: T;
  items?:
    | T
    | {
        label?: T;
        note?: T;
        file?: T;
        id?: T;
      };
  background?: T;
  spacing?: T;
  anchor?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "LogosBlock_select".
 */
export interface LogosBlockSelect<T extends boolean = true> {
  hidden?: T;
  eyebrow?: T;
  heading?: T;
  items?:
    | T
    | {
        name?: T;
        tier?: T;
        url?: T;
        logo?: T;
        id?: T;
      };
  background?: T;
  spacing?: T;
  anchor?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "VideoBlock_select".
 */
export interface VideoBlockSelect<T extends boolean = true> {
  hidden?: T;
  eyebrow?: T;
  heading?: T;
  youtube?: T;
  caption?: T;
  background?: T;
  spacing?: T;
  anchor?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "PageLinksBlock_select".
 */
export interface PageLinksBlockSelect<T extends boolean = true> {
  hidden?: T;
  eyebrow?: T;
  heading?: T;
  pages?: T;
  background?: T;
  spacing?: T;
  anchor?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ScheduleBlock_select".
 */
export interface ScheduleBlockSelect<T extends boolean = true> {
  hidden?: T;
  eyebrow?: T;
  heading?: T;
  intro?: T;
  days?:
    | T
    | {
        label?: T;
        date?: T;
        slots?:
          | T
          | {
              time?: T;
              end?: T;
              kind?: T;
              title?: T;
              speaker?: T;
              room?: T;
              description?: T;
              id?: T;
            };
        id?: T;
      };
  background?: T;
  spacing?: T;
  anchor?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "SpeakersBlock_select".
 */
export interface SpeakersBlockSelect<T extends boolean = true> {
  hidden?: T;
  eyebrow?: T;
  heading?: T;
  columns?: T;
  items?:
    | T
    | {
        name?: T;
        position?: T;
        affiliation?: T;
        talk?: T;
        photo?: T;
        bio?: T;
        link?: T;
        id?: T;
      };
  background?: T;
  spacing?: T;
  anchor?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FeesBlock_select".
 */
export interface FeesBlockSelect<T extends boolean = true> {
  hidden?: T;
  eyebrow?: T;
  heading?: T;
  intro?: T;
  column1?: T;
  column2?: T;
  column3?: T;
  rows?:
    | T
    | {
        category?: T;
        highlight?: T;
        note?: T;
        price1?: T;
        price2?: T;
        price3?: T;
        id?: T;
      };
  footnote?: T;
  buttons?:
    | T
    | {
        label?: T;
        url?: T;
        variant?: T;
        id?: T;
      };
  background?: T;
  spacing?: T;
  anchor?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "VenueBlock_select".
 */
export interface VenueBlockSelect<T extends boolean = true> {
  hidden?: T;
  eyebrow?: T;
  heading?: T;
  venueName?: T;
  mapQuery?: T;
  address?: T;
  image?: T;
  showMap?: T;
  notes?:
    | T
    | {
        title?: T;
        text?: T;
        id?: T;
      };
  background?: T;
  spacing?: T;
  anchor?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CtaBlock_select".
 */
export interface CtaBlockSelect<T extends boolean = true> {
  hidden?: T;
  heading?: T;
  text?: T;
  buttons?:
    | T
    | {
        label?: T;
        url?: T;
        variant?: T;
        id?: T;
      };
  anchor?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  template?: T;
  layout?:
    | T
    | {
        hero?: T | HeroBlockSelect<T>;
        text?: T | TextBlockSelect<T>;
        mediaText?: T | MediaTextBlockSelect<T>;
        cards?: T | CardsBlockSelect<T>;
        stats?: T | StatsBlockSelect<T>;
        timeline?: T | TimelineBlockSelect<T>;
        gallery?: T | GalleryBlockSelect<T>;
        events?: T | EventsBlockSelect<T>;
        stories?: T | StoriesBlockSelect<T>;
        people?: T | PeopleBlockSelect<T>;
        faq?: T | FaqBlockSelect<T>;
        form?: T | FormBlockSelect<T>;
        downloads?: T | DownloadsBlockSelect<T>;
        logos?: T | LogosBlockSelect<T>;
        video?: T | VideoBlockSelect<T>;
        pageLinks?: T | PageLinksBlockSelect<T>;
        schedule?: T | ScheduleBlockSelect<T>;
        speakers?: T | SpeakersBlockSelect<T>;
        fees?: T | FeesBlockSelect<T>;
        venue?: T | VenueBlockSelect<T>;
        cta?: T | CtaBlockSelect<T>;
      };
  summary?: T;
  cover?: T;
  accent?: T;
  showInNav?: T;
  order?: T;
  parent?: T;
  metaTitle?: T;
  metaDescription?: T;
  slug?: T;
  path?: T;
  shortPath?: T;
  url?: T;
  chapter?: T;
  updatedAt?: T;
  createdAt?: T;
  deletedAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HeroBlock_select".
 */
export interface HeroBlockSelect<T extends boolean = true> {
  hidden?: T;
  eyebrow?: T;
  heading?: T;
  text?: T;
  image?: T;
  dateLabel?: T;
  countdownTo?: T;
  buttons?:
    | T
    | {
        label?: T;
        url?: T;
        variant?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "committees_select".
 */
export interface CommitteesSelect<T extends boolean = true> {
  title?: T;
  term?: T;
  current?: T;
  advisors?:
    | T
    | {
        name?: T;
        position?: T;
        photo?: T;
        linkedin?: T;
        id?: T;
      };
  executive?:
    | T
    | {
        position?: T;
        name?: T;
        photo?: T;
        linkedin?: T;
        email?: T;
        id?: T;
      };
  teams?:
    | T
    | {
        name?: T;
        members?:
          | T
          | {
              name?: T;
              role?: T;
              position?: T;
              photo?: T;
              id?: T;
            };
        id?: T;
      };
  chapter?: T;
  updatedAt?: T;
  createdAt?: T;
  deletedAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "forms_select".
 */
export interface FormsSelect<T extends boolean = true> {
  title?: T;
  intro?: T;
  fields?:
    | T
    | {
        shortText?:
          | T
          | {
              label?: T;
              width?: T;
              required?: T;
              help?: T;
              name?: T;
              placeholder?: T;
              id?: T;
              blockName?: T;
            };
        email?:
          | T
          | {
              label?: T;
              width?: T;
              required?: T;
              help?: T;
              name?: T;
              id?: T;
              blockName?: T;
            };
        phone?:
          | T
          | {
              label?: T;
              width?: T;
              required?: T;
              help?: T;
              name?: T;
              id?: T;
              blockName?: T;
            };
        number?:
          | T
          | {
              label?: T;
              width?: T;
              required?: T;
              help?: T;
              name?: T;
              min?: T;
              max?: T;
              id?: T;
              blockName?: T;
            };
        longText?:
          | T
          | {
              label?: T;
              width?: T;
              required?: T;
              help?: T;
              name?: T;
              placeholder?: T;
              id?: T;
              blockName?: T;
            };
        select?:
          | T
          | {
              label?: T;
              width?: T;
              required?: T;
              help?: T;
              name?: T;
              options?:
                | T
                | {
                    label?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        radio?:
          | T
          | {
              label?: T;
              width?: T;
              required?: T;
              help?: T;
              name?: T;
              options?:
                | T
                | {
                    label?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        checkboxes?:
          | T
          | {
              label?: T;
              width?: T;
              required?: T;
              help?: T;
              name?: T;
              options?:
                | T
                | {
                    label?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        date?:
          | T
          | {
              label?: T;
              width?: T;
              required?: T;
              help?: T;
              name?: T;
              id?: T;
              blockName?: T;
            };
        url?:
          | T
          | {
              label?: T;
              width?: T;
              required?: T;
              help?: T;
              name?: T;
              id?: T;
              blockName?: T;
            };
        consent?:
          | T
          | {
              label?: T;
              width?: T;
              required?: T;
              help?: T;
              name?: T;
              id?: T;
              blockName?: T;
            };
        section?:
          | T
          | {
              label?: T;
              help?: T;
              id?: T;
              blockName?: T;
            };
      };
  submitLabel?: T;
  confirmationTitle?: T;
  confirmationMessage?: T;
  opensAt?: T;
  closesAt?: T;
  maxResponses?: T;
  onePerEmail?: T;
  status?: T;
  slug?: T;
  chapter?: T;
  updatedAt?: T;
  createdAt?: T;
  deletedAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-submissions_select".
 */
export interface FormSubmissionsSelect<T extends boolean = true> {
  summary?: T;
  form?: T;
  email?: T;
  data?: T;
  chapter?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  title?: T;
  kind?: T;
  date?: T;
  excerpt?: T;
  cover?: T;
  content?: T;
  gallery?: T;
  cta?:
    | T
    | {
        label?: T;
        url?: T;
      };
  slug?: T;
  chapter?: T;
  featureRequest?: T;
  featured?: T;
  updatedAt?: T;
  createdAt?: T;
  deletedAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events_select".
 */
export interface EventsSelect<T extends boolean = true> {
  title?: T;
  start?: T;
  end?: T;
  category?: T;
  summary?: T;
  descriptionHtml?: T;
  venue?: T;
  city?: T;
  virtual?: T;
  registrationUrl?: T;
  vtoolsUrl?: T;
  cover?: T;
  gallery?: T;
  vtoolsMediaDone?: T;
  hidden?: T;
  source?: T;
  vtoolsId?: T;
  hostName?: T;
  syncedAt?: T;
  slug?: T;
  chapter?: T;
  featureRequest?: T;
  featured?: T;
  updatedAt?: T;
  createdAt?: T;
  deletedAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "albums_select".
 */
export interface AlbumsSelect<T extends boolean = true> {
  title?: T;
  date?: T;
  description?: T;
  photos?: T;
  slug?: T;
  chapter?: T;
  updatedAt?: T;
  createdAt?: T;
  deletedAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  credit?: T;
  chapter?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumb?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        hero?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "documents_select".
 */
export interface DocumentsSelect<T extends boolean = true> {
  title?: T;
  chapter?: T;
  updatedAt?: T;
  createdAt?: T;
  deletedAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "programs_select".
 */
export interface ProgramsSelect<T extends boolean = true> {
  name?: T;
  edition?: T;
  slug?: T;
  tagline?: T;
  summary?: T;
  accent?: T;
  order?: T;
  cover?: T;
  logo?: T;
  stats?:
    | T
    | {
        value?: T;
        label?: T;
        id?: T;
      };
  sections?:
    | T
    | {
        heading?: T;
        body?: T;
        points?:
          | T
          | {
              text?: T;
              id?: T;
            };
        id?: T;
      };
  links?:
    | T
    | {
        label?: T;
        url?: T;
        primary?: T;
        id?: T;
      };
  contacts?:
    | T
    | {
        name?: T;
        role?: T;
        email?: T;
        id?: T;
      };
  gallery?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "people_select".
 */
export interface PeopleSelect<T extends boolean = true> {
  name?: T;
  position?: T;
  group?: T;
  team?: T;
  order?: T;
  photo?: T;
  term?: T;
  linkedin?: T;
  email?: T;
  archived?: T;
  chapter?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  chapter?: T;
  termEnds?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  resetPasswordRequestedAt?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "page-views_select".
 */
export interface PageViewsSelect<T extends boolean = true> {
  day?: T;
  path?: T;
  chapter?: T;
  source?: T;
  device?: T;
  visitor?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * Branch-wide settings. Branch webmasters only.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  spotlight?: {
    active?: boolean | null;
    /**
     * “Take over” replaces the big home-page header while the spotlight is on.
     */
    style?: ('banner' | 'hero') | null;
    /**
     * Optional — starts showing at this time
     */
    showFrom?: string | null;
    /**
     * Optional — hides itself after this, e.g. the last conference day
     */
    showUntil?: string | null;
    linkType?: ('page' | 'url') | null;
    /**
     * It must be published. Its title, card text, cover and colour fill anything left empty below.
     */
    page?: (number | null) | Page;
    url?: string | null;
    /**
     * Small label above the title
     */
    eyebrow?: string | null;
    /**
     * Leave empty to use the linked page’s title.
     */
    title?: string | null;
    /**
     * One or two sentences. Empty: the page’s card text.
     */
    text?: string | null;
    dateLabel?: string | null;
    venue?: string | null;
    /**
     * Optional live countdown, e.g. to the paper deadline
     */
    countdownTo?: string | null;
    /**
     * Words above the countdown
     */
    countdownLabel?: string | null;
    /**
     * A wide photo (≥ 1920 px) or the poster — posters are never cropped
     */
    image?: (number | null) | Media;
    /**
     * Optional event logo (transparent PNG)
     */
    logo?: (number | null) | Media;
    /**
     * Defaults to the linked page’s colour, else IEEE blue.
     */
    accent?: string | null;
    /**
     * Up to 3. With none, a single “Learn more” button opens the link above.
     */
    buttons?:
      | {
          label: string;
          /**
           * https://… or /chapters/…
           */
          url: string;
          variant?: ('primary' | 'secondary') | null;
          id?: string | null;
        }[]
      | null;
    /**
     * When the announcement bar is off
     */
    inTopBar?: boolean | null;
    topBarText?: string | null;
    inMenu?: boolean | null;
    menuLabel?: string | null;
  };
  heroKicker?: string | null;
  heroTitle?: string | null;
  heroAccent?: string | null;
  heroText?: string | null;
  announcement?: {
    active?: boolean | null;
    text?: string | null;
    url?: string | null;
  };
  stats?:
    | {
        value: string;
        suffix?: string | null;
        label: string;
        id?: string | null;
      }[]
    | null;
  vision?: string | null;
  mission?: string | null;
  showreel?: string | null;
  email?: string | null;
  address?: string | null;
  facebook?: string | null;
  instagram?: string | null;
  linkedin?: string | null;
  youtube?: string | null;
  volunteerForm?: string | null;
  /**
   * Leave empty to use only the built-in analytics. Google Analytics sets cookies.
   */
  googleAnalyticsId?: string | null;
  vtoolsEnabled?: boolean | null;
  /**
   * Chapter SPOIDs are set on each chapter.
   */
  vtoolsBranchSpoid?: string | null;
  /**
   * Backup rule: co-hosted events whose host name contains this text count as ours. vTools spells some units "Peradeniy", so keep it short.
   */
  vtoolsHostMatch?: string | null;
  /**
   * Untick to import every unit’s complete vTools history again on the next sync.
   */
  vtoolsHistoryImported?: boolean | null;
  vtoolsLastSync?: string | null;
  vtoolsLastResult?: string | null;
  vtoolsRunning?: boolean | null;
  vtoolsIgnored?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  dataVersion?: number | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  spotlight?:
    | T
    | {
        active?: T;
        style?: T;
        showFrom?: T;
        showUntil?: T;
        linkType?: T;
        page?: T;
        url?: T;
        eyebrow?: T;
        title?: T;
        text?: T;
        dateLabel?: T;
        venue?: T;
        countdownTo?: T;
        countdownLabel?: T;
        image?: T;
        logo?: T;
        accent?: T;
        buttons?:
          | T
          | {
              label?: T;
              url?: T;
              variant?: T;
              id?: T;
            };
        inTopBar?: T;
        topBarText?: T;
        inMenu?: T;
        menuLabel?: T;
      };
  heroKicker?: T;
  heroTitle?: T;
  heroAccent?: T;
  heroText?: T;
  announcement?:
    | T
    | {
        active?: T;
        text?: T;
        url?: T;
      };
  stats?:
    | T
    | {
        value?: T;
        suffix?: T;
        label?: T;
        id?: T;
      };
  vision?: T;
  mission?: T;
  showreel?: T;
  email?: T;
  address?: T;
  facebook?: T;
  instagram?: T;
  linkedin?: T;
  youtube?: T;
  volunteerForm?: T;
  googleAnalyticsId?: T;
  vtoolsEnabled?: T;
  vtoolsBranchSpoid?: T;
  vtoolsHostMatch?: T;
  vtoolsHistoryImported?: T;
  vtoolsLastSync?: T;
  vtoolsLastResult?: T;
  vtoolsRunning?: T;
  vtoolsIgnored?: T;
  dataVersion?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


